[package]
name = "FaceTraner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
opencv = "0.77.0"
tokio = "1.26.0"
